language: ruby
rvm:
  - 2.4.1

before_script:
  - chmod +x ./script/cibuild.sh
  - git clone https://${GH_REF} _site

script: ./script/cibuild.sh

branches:
  only:
  - develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true #

sudo: false

cache: bundler

after_script:
  - cd _site
  - git config user.name "dbdd4us"
  - git config user.email "wangtong2712@gmail.com"
  - git add .
  - git commit -m "Auto push from travis ci."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/dbdd4us/dbdd4us.github.io
